# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' OGR API
#'
#' OGR API tutorial minimal example
#' @export
#' @return integer
#' @examples
ogr_api <- function() {
    .Call('_gdalmin_ogr_api', PACKAGE = 'gdalmin')
}

open_as_vrt <- function(dsn, a_ullr) {
    .Call('_gdalmin_open_as_vrt', PACKAGE = 'gdalmin', dsn, a_ullr)
}

open_sds <- function(dsn, sds) {
    .Call('_gdalmin_open_sds', PACKAGE = 'gdalmin', dsn, sds)
}

