# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

open_to_vrt <- function(dsn, extent, projection, sds) {
    .Call('_gdalmin_open_to_vrt', PACKAGE = 'gdalmin', dsn, extent, projection, sds)
}

gm_GDALOpenShared <- function(dsn) {
    .Call('_gdalmin_gm_GDALOpenShared', PACKAGE = 'gdalmin', dsn)
}

gm_GetDescription <- function(xp) {
    .Call('_gdalmin_gm_GetDescription', PACKAGE = 'gdalmin', xp)
}

gm_chr <- function(xp) {
    .Call('_gdalmin_gm_chr', PACKAGE = 'gdalmin', xp)
}

gm_GetRasterXSize <- function(xp) {
    .Call('_gdalmin_gm_GetRasterXSize', PACKAGE = 'gdalmin', xp)
}

gm_GetRasterYSize <- function(xp) {
    .Call('_gdalmin_gm_GetRasterYSize', PACKAGE = 'gdalmin', xp)
}

gm_GetRasterCount <- function(xp) {
    .Call('_gdalmin_gm_GetRasterCount', PACKAGE = 'gdalmin', xp)
}

gm_GetGCPCount <- function(xp) {
    .Call('_gdalmin_gm_GetGCPCount', PACKAGE = 'gdalmin', xp)
}

gm_Reference <- function(xp) {
    .Call('_gdalmin_gm_Reference', PACKAGE = 'gdalmin', xp)
}

gm_Dereference <- function(xp) {
    .Call('_gdalmin_gm_Dereference', PACKAGE = 'gdalmin', xp)
}

gm_ReleaseRef <- function(xp) {
    .Call('_gdalmin_gm_ReleaseRef', PACKAGE = 'gdalmin', xp)
}

gm_GetRefCount <- function(xp) {
    .Call('_gdalmin_gm_GetRefCount', PACKAGE = 'gdalmin', xp)
}

gm_GetSummaryRefCount <- function(xp) {
    .Call('_gdalmin_gm_GetSummaryRefCount', PACKAGE = 'gdalmin', xp)
}

gm_GetShared <- function(xp) {
    .Call('_gdalmin_gm_GetShared', PACKAGE = 'gdalmin', xp)
}

gm_TestCapability <- function(xp, capability) {
    .Call('_gdalmin_gm_TestCapability', PACKAGE = 'gdalmin', xp, capability)
}

#' OGR API
#'
#' OGR API tutorial minimal example
#' @export
#' @return integer
#' @examples
ogr_api <- function() {
    .Call('_gdalmin_ogr_api', PACKAGE = 'gdalmin')
}

open_as_vrt <- function(dsn, extent, projection, sds) {
    .Call('_gdalmin_open_as_vrt', PACKAGE = 'gdalmin', dsn, extent, projection, sds)
}

not_die1 <- function(proj) {
    .Call('_gdalmin_not_die1', PACKAGE = 'gdalmin', proj)
}

do_die1 <- function(proj) {
    .Call('_gdalmin_do_die1', PACKAGE = 'gdalmin', proj)
}

