# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' OGR API
#'
#' OGR API tutorial minimal example
#' @export
#' @return integer
#' @examples
ogr_api <- function() {
    .Call('_gdalmin_ogr_api', PACKAGE = 'gdalmin')
}

